// Package server implements api.StrictServerInterface.
//
// Handlers are intentionally thin: they translate the generated request object
// into a repo.Filter or an id, call the generic service, and wrap the result in
// the operation's typed success response. All error-to-HTTP-status mapping is
// centralized in the ErrorMiddleware (errors.go); handlers just return an error.
//
// This file is generated by scratchpad/gen_handlers.py. Regenerate rather than
// hand-editing the repetitive resource handlers.
package server

import (
	"context"

	"github.com/rxtech-lab/railway-wiki/internal/api"
	"github.com/rxtech-lab/railway-wiki/internal/convert"
	"github.com/rxtech-lab/railway-wiki/internal/media"
	"github.com/rxtech-lab/railway-wiki/internal/models"
	"github.com/rxtech-lab/railway-wiki/internal/repo"
	"github.com/rxtech-lab/railway-wiki/internal/schema"
	"github.com/rxtech-lab/railway-wiki/internal/service"
	"gorm.io/gorm"
)

// Ensure Server implements StrictServerInterface.
var _ api.StrictServerInterface = (*Server)(nil)

// Per-resource service type aliases.
type svcCompany = *service.Service[models.Company, *models.Company, api.Company, api.CreateCompanyRequest, api.UpdateCompanyRequest]
type svcStation = *service.Service[models.Station, *models.Station, api.Station, api.CreateStationRequest, api.UpdateStationRequest]
type svcStationCode = *service.Service[models.StationCode, *models.StationCode, api.StationCode, api.CreateStationCodeRequest, api.UpdateStationCodeRequest]
type svcStationTransfer = *service.Service[models.StationTransfer, *models.StationTransfer, api.StationTransfer, api.CreateStationTransferRequest, api.UpdateStationTransferRequest]
type svcPlatform = *service.Service[models.Platform, *models.Platform, api.Platform, api.CreatePlatformRequest, api.UpdatePlatformRequest]
type svcRoute = *service.Service[models.Route, *models.Route, api.Route, api.CreateRouteRequest, api.UpdateRouteRequest]
type svcRouteCompany = *service.Service[models.RouteCompany, *models.RouteCompany, api.RouteCompany, api.CreateRouteCompanyRequest, api.UpdateRouteCompanyRequest]
type svcRouteStation = *service.Service[models.RouteStation, *models.RouteStation, api.RouteStation, api.CreateRouteStationRequest, api.UpdateRouteStationRequest]
type svcTrackSegment = *service.Service[models.TrackSegment, *models.TrackSegment, api.TrackSegment, api.CreateTrackSegmentRequest, api.UpdateTrackSegmentRequest]
type svcPlatformTrack = *service.Service[models.PlatformTrack, *models.PlatformTrack, api.PlatformTrack, api.CreatePlatformTrackRequest, api.UpdatePlatformTrackRequest]
type svcOperationRoute = *service.Service[models.OperationRoute, *models.OperationRoute, api.OperationRoute, api.CreateOperationRouteRequest, api.UpdateOperationRouteRequest]
type svcOperationRouteCompany = *service.Service[models.OperationRouteCompany, *models.OperationRouteCompany, api.OperationRouteCompany, api.CreateOperationRouteCompanyRequest, api.UpdateOperationRouteCompanyRequest]
type svcOperationRouteSection = *service.Service[models.OperationRouteSection, *models.OperationRouteSection, api.OperationRouteSection, api.CreateOperationRouteSectionRequest, api.UpdateOperationRouteSectionRequest]
type svcOperationRouteStop = *service.Service[models.OperationRouteStop, *models.OperationRouteStop, api.OperationRouteStop, api.CreateOperationRouteStopRequest, api.UpdateOperationRouteStopRequest]
type svcTimetableVersion = *service.Service[models.TimetableVersion, *models.TimetableVersion, api.TimetableVersion, api.CreateTimetableVersionRequest, api.UpdateTimetableVersionRequest]
type svcServiceCalendar = *service.Service[models.ServiceCalendar, *models.ServiceCalendar, api.ServiceCalendar, api.CreateServiceCalendarRequest, api.UpdateServiceCalendarRequest]
type svcServiceCalendarException = *service.Service[models.ServiceCalendarException, *models.ServiceCalendarException, api.ServiceCalendarException, api.CreateServiceCalendarExceptionRequest, api.UpdateServiceCalendarExceptionRequest]
type svcTrain = *service.Service[models.Train, *models.Train, api.Train, api.CreateTrainRequest, api.UpdateTrainRequest]
type svcTrainRun = *service.Service[models.TrainRun, *models.TrainRun, api.TrainRun, api.CreateTrainRunRequest, api.UpdateTrainRunRequest]
type svcTrainRunStop = *service.Service[models.TrainRunStop, *models.TrainRunStop, api.TrainRunStop, api.CreateTrainRunStopRequest, api.UpdateTrainRunStopRequest]
type svcMedia = *service.Service[models.Media, *models.Media, api.Media, api.CreateMediaRequest, api.UpdateMediaRequest]
type svcMediaAttachment = *service.Service[models.MediaAttachment, *models.MediaAttachment, api.MediaAttachment, api.CreateMediaAttachmentRequest, api.UpdateMediaAttachmentRequest]

// Server holds every resource service plus infra dependencies.
type Server struct {
	schemas                   *schema.Registry
	presign                   media.Presigner
	companies                 svcCompany
	stations                  svcStation
	stationCodes              svcStationCode
	stationTransfers          svcStationTransfer
	platforms                 svcPlatform
	routes                    svcRoute
	routeCompanies            svcRouteCompany
	routeStations             svcRouteStation
	trackSegments             svcTrackSegment
	platformTracks            svcPlatformTrack
	operationRoutes           svcOperationRoute
	operationRouteCompanies   svcOperationRouteCompany
	operationRouteSections    svcOperationRouteSection
	operationRouteStops       svcOperationRouteStop
	timetableVersions         svcTimetableVersion
	serviceCalendars          svcServiceCalendar
	serviceCalendarExceptions svcServiceCalendarException
	trains                    svcTrain
	trainRuns                 svcTrainRun
	trainRunStops             svcTrainRunStop
	media                     svcMedia
	mediaAttachments          svcMediaAttachment
}

// NewServer builds the Server, constructing all resource services from db.
func NewServer(db *gorm.DB, presign media.Presigner, schemas *schema.Registry) *Server {
	return &Server{
		schemas:                   schemas,
		presign:                   presign,
		companies:                 service.New(repo.New[models.Company](db, "name", "short_name"), convert.CompanyToAPI, convert.CompanyFromCreate, convert.CompanyApplyUpdate),
		stations:                  service.New(repo.New[models.Station](db, "name", "name_en"), convert.StationToAPI, convert.StationFromCreate, convert.StationApplyUpdate),
		stationCodes:              service.New(repo.New[models.StationCode](db), convert.StationCodeToAPI, convert.StationCodeFromCreate, convert.StationCodeApplyUpdate),
		stationTransfers:          service.New(repo.New[models.StationTransfer](db), convert.StationTransferToAPI, convert.StationTransferFromCreate, convert.StationTransferApplyUpdate),
		platforms:                 service.New(repo.New[models.Platform](db), convert.PlatformToAPI, convert.PlatformFromCreate, convert.PlatformApplyUpdate),
		routes:                    service.New(repo.New[models.Route](db, "name", "name_en"), convert.RouteToAPI, convert.RouteFromCreate, convert.RouteApplyUpdate),
		routeCompanies:            service.New(repo.New[models.RouteCompany](db), convert.RouteCompanyToAPI, convert.RouteCompanyFromCreate, convert.RouteCompanyApplyUpdate),
		routeStations:             service.New(repo.New[models.RouteStation](db), convert.RouteStationToAPI, convert.RouteStationFromCreate, convert.RouteStationApplyUpdate),
		trackSegments:             service.New(repo.New[models.TrackSegment](db), convert.TrackSegmentToAPI, convert.TrackSegmentFromCreate, convert.TrackSegmentApplyUpdate),
		platformTracks:            service.New(repo.New[models.PlatformTrack](db), convert.PlatformTrackToAPI, convert.PlatformTrackFromCreate, convert.PlatformTrackApplyUpdate),
		operationRoutes:           service.New(repo.New[models.OperationRoute](db, "name", "name_en"), convert.OperationRouteToAPI, convert.OperationRouteFromCreate, convert.OperationRouteApplyUpdate),
		operationRouteCompanies:   service.New(repo.New[models.OperationRouteCompany](db), convert.OperationRouteCompanyToAPI, convert.OperationRouteCompanyFromCreate, convert.OperationRouteCompanyApplyUpdate),
		operationRouteSections:    service.New(repo.New[models.OperationRouteSection](db), convert.OperationRouteSectionToAPI, convert.OperationRouteSectionFromCreate, convert.OperationRouteSectionApplyUpdate),
		operationRouteStops:       service.New(repo.New[models.OperationRouteStop](db), convert.OperationRouteStopToAPI, convert.OperationRouteStopFromCreate, convert.OperationRouteStopApplyUpdate),
		timetableVersions:         service.New(repo.New[models.TimetableVersion](db, "name"), convert.TimetableVersionToAPI, convert.TimetableVersionFromCreate, convert.TimetableVersionApplyUpdate),
		serviceCalendars:          service.New(repo.New[models.ServiceCalendar](db, "name"), convert.ServiceCalendarToAPI, convert.ServiceCalendarFromCreate, convert.ServiceCalendarApplyUpdate),
		serviceCalendarExceptions: service.New(repo.New[models.ServiceCalendarException](db), convert.ServiceCalendarExceptionToAPI, convert.ServiceCalendarExceptionFromCreate, convert.ServiceCalendarExceptionApplyUpdate),
		trains:                    service.New(repo.New[models.Train](db, "train_number", "train_name"), convert.TrainToAPI, convert.TrainFromCreate, convert.TrainApplyUpdate),
		trainRuns:                 service.New(repo.New[models.TrainRun](db), convert.TrainRunToAPI, convert.TrainRunFromCreate, convert.TrainRunApplyUpdate),
		trainRunStops:             service.New(repo.New[models.TrainRunStop](db), convert.TrainRunStopToAPI, convert.TrainRunStopFromCreate, convert.TrainRunStopApplyUpdate),
		media:                     service.New(repo.New[models.Media](db, "title"), convert.MediaToAPI, convert.MediaFromCreate, convert.MediaApplyUpdate),
		mediaAttachments:          service.New(repo.New[models.MediaAttachment](db), convert.MediaAttachmentToAPI, convert.MediaAttachmentFromCreate, convert.MediaAttachmentApplyUpdate),
	}
}

// GetHealth reports service health.
func (s *Server) GetHealth(ctx context.Context, r api.GetHealthRequestObject) (api.GetHealthResponseObject, error) {
	return api.GetHealth200JSONResponse{Status: "ok"}, nil
}

// AdminCreateMediaUploadUrl returns a presigned upload target for a media file.
func (s *Server) AdminCreateMediaUploadUrl(ctx context.Context, r api.AdminCreateMediaUploadUrlRequestObject) (api.AdminCreateMediaUploadUrlResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	target, err := s.presign.Presign(ctx, media.PresignInput{
		FileName:    r.Body.FileName,
		ContentType: r.Body.ContentType,
		MediaType:   r.Body.MediaType,
		SizeBytes:   r.Body.SizeBytes,
	})
	if err != nil {
		return nil, err
	}
	return api.AdminCreateMediaUploadUrl201JSONResponse(*target), nil
}

// --- Company ---

func (s *Server) ListCompanies(ctx context.Context, r api.ListCompaniesRequestObject) (api.ListCompaniesResponseObject, error) {
	items, next, err := s.companies.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetCompany(ctx context.Context, r api.GetCompanyRequestObject) (api.GetCompanyResponseObject, error) {
	m, err := s.companies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetCompany200JSONResponse(*m), nil
}

func (s *Server) AdminListCompanies(ctx context.Context, r api.AdminListCompaniesRequestObject) (api.AdminListCompaniesResponseObject, error) {
	items, next, err := s.companies.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetCompany(ctx context.Context, r api.AdminGetCompanyRequestObject) (api.AdminGetCompanyResponseObject, error) {
	m, err := s.companies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetCompany200JSONResponse(*m), nil
}

func (s *Server) AdminCreateCompany(ctx context.Context, r api.AdminCreateCompanyRequestObject) (api.AdminCreateCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.companies.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateCompany201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateCompany(ctx context.Context, r api.AdminUpdateCompanyRequestObject) (api.AdminUpdateCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.companies.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateCompany200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteCompany(ctx context.Context, r api.AdminDeleteCompanyRequestObject) (api.AdminDeleteCompanyResponseObject, error) {
	if err := s.companies.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteCompany204Response{}, nil
}

func (s *Server) AdminGetCompanySchema(ctx context.Context, r api.AdminGetCompanySchemaRequestObject) (api.AdminGetCompanySchemaResponseObject, error) {
	return api.AdminGetCompanySchema200JSONResponse(s.schemas.For("Company", string(r.Params.Action))), nil
}

// --- Station ---

func (s *Server) ListStations(ctx context.Context, r api.ListStationsRequestObject) (api.ListStationsResponseObject, error) {
	items, next, err := s.stations.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListStations200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetStation(ctx context.Context, r api.GetStationRequestObject) (api.GetStationResponseObject, error) {
	m, err := s.stations.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetStation200JSONResponse(*m), nil
}

func (s *Server) AdminListStations(ctx context.Context, r api.AdminListStationsRequestObject) (api.AdminListStationsResponseObject, error) {
	items, next, err := s.stations.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListStations200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetStation(ctx context.Context, r api.AdminGetStationRequestObject) (api.AdminGetStationResponseObject, error) {
	m, err := s.stations.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetStation200JSONResponse(*m), nil
}

func (s *Server) AdminCreateStation(ctx context.Context, r api.AdminCreateStationRequestObject) (api.AdminCreateStationResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stations.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateStation201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateStation(ctx context.Context, r api.AdminUpdateStationRequestObject) (api.AdminUpdateStationResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stations.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateStation200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteStation(ctx context.Context, r api.AdminDeleteStationRequestObject) (api.AdminDeleteStationResponseObject, error) {
	if err := s.stations.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteStation204Response{}, nil
}

func (s *Server) AdminGetStationSchema(ctx context.Context, r api.AdminGetStationSchemaRequestObject) (api.AdminGetStationSchemaResponseObject, error) {
	return api.AdminGetStationSchema200JSONResponse(s.schemas.For("Station", string(r.Params.Action))), nil
}

// --- StationCode ---

func (s *Server) ListStationCodes(ctx context.Context, r api.ListStationCodesRequestObject) (api.ListStationCodesResponseObject, error) {
	items, next, err := s.stationCodes.List(ctx, repo.Filter{Eq: map[string]any{"station_id": r.Params.StationId, "route_id": r.Params.RouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListStationCodes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetStationCode(ctx context.Context, r api.GetStationCodeRequestObject) (api.GetStationCodeResponseObject, error) {
	m, err := s.stationCodes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetStationCode200JSONResponse(*m), nil
}

func (s *Server) AdminListStationCodes(ctx context.Context, r api.AdminListStationCodesRequestObject) (api.AdminListStationCodesResponseObject, error) {
	items, next, err := s.stationCodes.List(ctx, repo.Filter{Eq: map[string]any{"station_id": r.Params.StationId, "route_id": r.Params.RouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListStationCodes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetStationCode(ctx context.Context, r api.AdminGetStationCodeRequestObject) (api.AdminGetStationCodeResponseObject, error) {
	m, err := s.stationCodes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetStationCode200JSONResponse(*m), nil
}

func (s *Server) AdminCreateStationCode(ctx context.Context, r api.AdminCreateStationCodeRequestObject) (api.AdminCreateStationCodeResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stationCodes.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateStationCode201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateStationCode(ctx context.Context, r api.AdminUpdateStationCodeRequestObject) (api.AdminUpdateStationCodeResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stationCodes.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateStationCode200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteStationCode(ctx context.Context, r api.AdminDeleteStationCodeRequestObject) (api.AdminDeleteStationCodeResponseObject, error) {
	if err := s.stationCodes.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteStationCode204Response{}, nil
}

func (s *Server) AdminGetStationCodeSchema(ctx context.Context, r api.AdminGetStationCodeSchemaRequestObject) (api.AdminGetStationCodeSchemaResponseObject, error) {
	return api.AdminGetStationCodeSchema200JSONResponse(s.schemas.For("StationCode", string(r.Params.Action))), nil
}

// --- StationTransfer ---

func (s *Server) ListStationTransfers(ctx context.Context, r api.ListStationTransfersRequestObject) (api.ListStationTransfersResponseObject, error) {
	items, next, err := s.stationTransfers.List(ctx, repo.Filter{Eq: map[string]any{"from_station_id": r.Params.FromStationId, "to_station_id": r.Params.ToStationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListStationTransfers200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetStationTransfer(ctx context.Context, r api.GetStationTransferRequestObject) (api.GetStationTransferResponseObject, error) {
	m, err := s.stationTransfers.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetStationTransfer200JSONResponse(*m), nil
}

func (s *Server) AdminListStationTransfers(ctx context.Context, r api.AdminListStationTransfersRequestObject) (api.AdminListStationTransfersResponseObject, error) {
	items, next, err := s.stationTransfers.List(ctx, repo.Filter{Eq: map[string]any{"from_station_id": r.Params.FromStationId, "to_station_id": r.Params.ToStationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListStationTransfers200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetStationTransfer(ctx context.Context, r api.AdminGetStationTransferRequestObject) (api.AdminGetStationTransferResponseObject, error) {
	m, err := s.stationTransfers.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetStationTransfer200JSONResponse(*m), nil
}

func (s *Server) AdminCreateStationTransfer(ctx context.Context, r api.AdminCreateStationTransferRequestObject) (api.AdminCreateStationTransferResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stationTransfers.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateStationTransfer201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateStationTransfer(ctx context.Context, r api.AdminUpdateStationTransferRequestObject) (api.AdminUpdateStationTransferResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.stationTransfers.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateStationTransfer200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteStationTransfer(ctx context.Context, r api.AdminDeleteStationTransferRequestObject) (api.AdminDeleteStationTransferResponseObject, error) {
	if err := s.stationTransfers.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteStationTransfer204Response{}, nil
}

func (s *Server) AdminGetStationTransferSchema(ctx context.Context, r api.AdminGetStationTransferSchemaRequestObject) (api.AdminGetStationTransferSchemaResponseObject, error) {
	return api.AdminGetStationTransferSchema200JSONResponse(s.schemas.For("StationTransfer", string(r.Params.Action))), nil
}

// --- Platform ---

func (s *Server) ListPlatforms(ctx context.Context, r api.ListPlatformsRequestObject) (api.ListPlatformsResponseObject, error) {
	items, next, err := s.platforms.List(ctx, repo.Filter{Eq: map[string]any{"station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListPlatforms200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetPlatform(ctx context.Context, r api.GetPlatformRequestObject) (api.GetPlatformResponseObject, error) {
	m, err := s.platforms.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetPlatform200JSONResponse(*m), nil
}

func (s *Server) AdminListPlatforms(ctx context.Context, r api.AdminListPlatformsRequestObject) (api.AdminListPlatformsResponseObject, error) {
	items, next, err := s.platforms.List(ctx, repo.Filter{Eq: map[string]any{"station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListPlatforms200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetPlatform(ctx context.Context, r api.AdminGetPlatformRequestObject) (api.AdminGetPlatformResponseObject, error) {
	m, err := s.platforms.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetPlatform200JSONResponse(*m), nil
}

func (s *Server) AdminCreatePlatform(ctx context.Context, r api.AdminCreatePlatformRequestObject) (api.AdminCreatePlatformResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.platforms.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreatePlatform201JSONResponse(*m), nil
}

func (s *Server) AdminUpdatePlatform(ctx context.Context, r api.AdminUpdatePlatformRequestObject) (api.AdminUpdatePlatformResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.platforms.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdatePlatform200JSONResponse(*m), nil
}

func (s *Server) AdminDeletePlatform(ctx context.Context, r api.AdminDeletePlatformRequestObject) (api.AdminDeletePlatformResponseObject, error) {
	if err := s.platforms.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeletePlatform204Response{}, nil
}

func (s *Server) AdminGetPlatformSchema(ctx context.Context, r api.AdminGetPlatformSchemaRequestObject) (api.AdminGetPlatformSchemaResponseObject, error) {
	return api.AdminGetPlatformSchema200JSONResponse(s.schemas.For("Platform", string(r.Params.Action))), nil
}

// --- Route ---

func (s *Server) ListRoutes(ctx context.Context, r api.ListRoutesRequestObject) (api.ListRoutesResponseObject, error) {
	items, next, err := s.routes.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListRoutes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetRoute(ctx context.Context, r api.GetRouteRequestObject) (api.GetRouteResponseObject, error) {
	m, err := s.routes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetRoute200JSONResponse(*m), nil
}

func (s *Server) AdminListRoutes(ctx context.Context, r api.AdminListRoutesRequestObject) (api.AdminListRoutesResponseObject, error) {
	items, next, err := s.routes.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListRoutes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetRoute(ctx context.Context, r api.AdminGetRouteRequestObject) (api.AdminGetRouteResponseObject, error) {
	m, err := s.routes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetRoute200JSONResponse(*m), nil
}

func (s *Server) AdminCreateRoute(ctx context.Context, r api.AdminCreateRouteRequestObject) (api.AdminCreateRouteResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routes.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateRoute201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateRoute(ctx context.Context, r api.AdminUpdateRouteRequestObject) (api.AdminUpdateRouteResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routes.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateRoute200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteRoute(ctx context.Context, r api.AdminDeleteRouteRequestObject) (api.AdminDeleteRouteResponseObject, error) {
	if err := s.routes.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteRoute204Response{}, nil
}

func (s *Server) AdminGetRouteSchema(ctx context.Context, r api.AdminGetRouteSchemaRequestObject) (api.AdminGetRouteSchemaResponseObject, error) {
	return api.AdminGetRouteSchema200JSONResponse(s.schemas.For("Route", string(r.Params.Action))), nil
}

// --- RouteCompany ---

func (s *Server) ListRouteCompanies(ctx context.Context, r api.ListRouteCompaniesRequestObject) (api.ListRouteCompaniesResponseObject, error) {
	items, next, err := s.routeCompanies.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListRouteCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetRouteCompany(ctx context.Context, r api.GetRouteCompanyRequestObject) (api.GetRouteCompanyResponseObject, error) {
	m, err := s.routeCompanies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminListRouteCompanies(ctx context.Context, r api.AdminListRouteCompaniesRequestObject) (api.AdminListRouteCompaniesResponseObject, error) {
	items, next, err := s.routeCompanies.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListRouteCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetRouteCompany(ctx context.Context, r api.AdminGetRouteCompanyRequestObject) (api.AdminGetRouteCompanyResponseObject, error) {
	m, err := s.routeCompanies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminCreateRouteCompany(ctx context.Context, r api.AdminCreateRouteCompanyRequestObject) (api.AdminCreateRouteCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routeCompanies.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateRouteCompany201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateRouteCompany(ctx context.Context, r api.AdminUpdateRouteCompanyRequestObject) (api.AdminUpdateRouteCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routeCompanies.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteRouteCompany(ctx context.Context, r api.AdminDeleteRouteCompanyRequestObject) (api.AdminDeleteRouteCompanyResponseObject, error) {
	if err := s.routeCompanies.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteRouteCompany204Response{}, nil
}

func (s *Server) AdminGetRouteCompanySchema(ctx context.Context, r api.AdminGetRouteCompanySchemaRequestObject) (api.AdminGetRouteCompanySchemaResponseObject, error) {
	return api.AdminGetRouteCompanySchema200JSONResponse(s.schemas.For("RouteCompany", string(r.Params.Action))), nil
}

// --- RouteStation ---

func (s *Server) ListRouteStations(ctx context.Context, r api.ListRouteStationsRequestObject) (api.ListRouteStationsResponseObject, error) {
	items, next, err := s.routeStations.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListRouteStations200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetRouteStation(ctx context.Context, r api.GetRouteStationRequestObject) (api.GetRouteStationResponseObject, error) {
	m, err := s.routeStations.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetRouteStation200JSONResponse(*m), nil
}

func (s *Server) AdminListRouteStations(ctx context.Context, r api.AdminListRouteStationsRequestObject) (api.AdminListRouteStationsResponseObject, error) {
	items, next, err := s.routeStations.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListRouteStations200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetRouteStation(ctx context.Context, r api.AdminGetRouteStationRequestObject) (api.AdminGetRouteStationResponseObject, error) {
	m, err := s.routeStations.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetRouteStation200JSONResponse(*m), nil
}

func (s *Server) AdminCreateRouteStation(ctx context.Context, r api.AdminCreateRouteStationRequestObject) (api.AdminCreateRouteStationResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routeStations.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateRouteStation201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateRouteStation(ctx context.Context, r api.AdminUpdateRouteStationRequestObject) (api.AdminUpdateRouteStationResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.routeStations.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateRouteStation200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteRouteStation(ctx context.Context, r api.AdminDeleteRouteStationRequestObject) (api.AdminDeleteRouteStationResponseObject, error) {
	if err := s.routeStations.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteRouteStation204Response{}, nil
}

func (s *Server) AdminGetRouteStationSchema(ctx context.Context, r api.AdminGetRouteStationSchemaRequestObject) (api.AdminGetRouteStationSchemaResponseObject, error) {
	return api.AdminGetRouteStationSchema200JSONResponse(s.schemas.For("RouteStation", string(r.Params.Action))), nil
}

// --- TrackSegment ---

func (s *Server) ListTrackSegments(ctx context.Context, r api.ListTrackSegmentsRequestObject) (api.ListTrackSegmentsResponseObject, error) {
	items, next, err := s.trackSegments.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "from_station_id": r.Params.FromStationId, "to_station_id": r.Params.ToStationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListTrackSegments200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetTrackSegment(ctx context.Context, r api.GetTrackSegmentRequestObject) (api.GetTrackSegmentResponseObject, error) {
	m, err := s.trackSegments.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetTrackSegment200JSONResponse(*m), nil
}

func (s *Server) AdminListTrackSegments(ctx context.Context, r api.AdminListTrackSegmentsRequestObject) (api.AdminListTrackSegmentsResponseObject, error) {
	items, next, err := s.trackSegments.List(ctx, repo.Filter{Eq: map[string]any{"route_id": r.Params.RouteId, "from_station_id": r.Params.FromStationId, "to_station_id": r.Params.ToStationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListTrackSegments200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetTrackSegment(ctx context.Context, r api.AdminGetTrackSegmentRequestObject) (api.AdminGetTrackSegmentResponseObject, error) {
	m, err := s.trackSegments.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetTrackSegment200JSONResponse(*m), nil
}

func (s *Server) AdminCreateTrackSegment(ctx context.Context, r api.AdminCreateTrackSegmentRequestObject) (api.AdminCreateTrackSegmentResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trackSegments.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateTrackSegment201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateTrackSegment(ctx context.Context, r api.AdminUpdateTrackSegmentRequestObject) (api.AdminUpdateTrackSegmentResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trackSegments.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateTrackSegment200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteTrackSegment(ctx context.Context, r api.AdminDeleteTrackSegmentRequestObject) (api.AdminDeleteTrackSegmentResponseObject, error) {
	if err := s.trackSegments.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteTrackSegment204Response{}, nil
}

func (s *Server) AdminGetTrackSegmentSchema(ctx context.Context, r api.AdminGetTrackSegmentSchemaRequestObject) (api.AdminGetTrackSegmentSchemaResponseObject, error) {
	return api.AdminGetTrackSegmentSchema200JSONResponse(s.schemas.For("TrackSegment", string(r.Params.Action))), nil
}

// --- PlatformTrack ---

func (s *Server) ListPlatformTracks(ctx context.Context, r api.ListPlatformTracksRequestObject) (api.ListPlatformTracksResponseObject, error) {
	items, next, err := s.platformTracks.List(ctx, repo.Filter{Eq: map[string]any{"platform_id": r.Params.PlatformId, "track_segment_id": r.Params.TrackSegmentId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListPlatformTracks200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetPlatformTrack(ctx context.Context, r api.GetPlatformTrackRequestObject) (api.GetPlatformTrackResponseObject, error) {
	m, err := s.platformTracks.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetPlatformTrack200JSONResponse(*m), nil
}

func (s *Server) AdminListPlatformTracks(ctx context.Context, r api.AdminListPlatformTracksRequestObject) (api.AdminListPlatformTracksResponseObject, error) {
	items, next, err := s.platformTracks.List(ctx, repo.Filter{Eq: map[string]any{"platform_id": r.Params.PlatformId, "track_segment_id": r.Params.TrackSegmentId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListPlatformTracks200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetPlatformTrack(ctx context.Context, r api.AdminGetPlatformTrackRequestObject) (api.AdminGetPlatformTrackResponseObject, error) {
	m, err := s.platformTracks.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetPlatformTrack200JSONResponse(*m), nil
}

func (s *Server) AdminCreatePlatformTrack(ctx context.Context, r api.AdminCreatePlatformTrackRequestObject) (api.AdminCreatePlatformTrackResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.platformTracks.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreatePlatformTrack201JSONResponse(*m), nil
}

func (s *Server) AdminUpdatePlatformTrack(ctx context.Context, r api.AdminUpdatePlatformTrackRequestObject) (api.AdminUpdatePlatformTrackResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.platformTracks.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdatePlatformTrack200JSONResponse(*m), nil
}

func (s *Server) AdminDeletePlatformTrack(ctx context.Context, r api.AdminDeletePlatformTrackRequestObject) (api.AdminDeletePlatformTrackResponseObject, error) {
	if err := s.platformTracks.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeletePlatformTrack204Response{}, nil
}

func (s *Server) AdminGetPlatformTrackSchema(ctx context.Context, r api.AdminGetPlatformTrackSchemaRequestObject) (api.AdminGetPlatformTrackSchemaResponseObject, error) {
	return api.AdminGetPlatformTrackSchema200JSONResponse(s.schemas.For("PlatformTrack", string(r.Params.Action))), nil
}

// --- OperationRoute ---

func (s *Server) ListOperationRoutes(ctx context.Context, r api.ListOperationRoutesRequestObject) (api.ListOperationRoutesResponseObject, error) {
	items, next, err := s.operationRoutes.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListOperationRoutes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetOperationRoute(ctx context.Context, r api.GetOperationRouteRequestObject) (api.GetOperationRouteResponseObject, error) {
	m, err := s.operationRoutes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetOperationRoute200JSONResponse(*m), nil
}

func (s *Server) AdminListOperationRoutes(ctx context.Context, r api.AdminListOperationRoutesRequestObject) (api.AdminListOperationRoutesResponseObject, error) {
	items, next, err := s.operationRoutes.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListOperationRoutes200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetOperationRoute(ctx context.Context, r api.AdminGetOperationRouteRequestObject) (api.AdminGetOperationRouteResponseObject, error) {
	m, err := s.operationRoutes.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetOperationRoute200JSONResponse(*m), nil
}

func (s *Server) AdminCreateOperationRoute(ctx context.Context, r api.AdminCreateOperationRouteRequestObject) (api.AdminCreateOperationRouteResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRoutes.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateOperationRoute201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateOperationRoute(ctx context.Context, r api.AdminUpdateOperationRouteRequestObject) (api.AdminUpdateOperationRouteResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRoutes.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateOperationRoute200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteOperationRoute(ctx context.Context, r api.AdminDeleteOperationRouteRequestObject) (api.AdminDeleteOperationRouteResponseObject, error) {
	if err := s.operationRoutes.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteOperationRoute204Response{}, nil
}

func (s *Server) AdminGetOperationRouteSchema(ctx context.Context, r api.AdminGetOperationRouteSchemaRequestObject) (api.AdminGetOperationRouteSchemaResponseObject, error) {
	return api.AdminGetOperationRouteSchema200JSONResponse(s.schemas.For("OperationRoute", string(r.Params.Action))), nil
}

// --- OperationRouteCompany ---

func (s *Server) ListOperationRouteCompanies(ctx context.Context, r api.ListOperationRouteCompaniesRequestObject) (api.ListOperationRouteCompaniesResponseObject, error) {
	items, next, err := s.operationRouteCompanies.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListOperationRouteCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetOperationRouteCompany(ctx context.Context, r api.GetOperationRouteCompanyRequestObject) (api.GetOperationRouteCompanyResponseObject, error) {
	m, err := s.operationRouteCompanies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetOperationRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminListOperationRouteCompanies(ctx context.Context, r api.AdminListOperationRouteCompaniesRequestObject) (api.AdminListOperationRouteCompaniesResponseObject, error) {
	items, next, err := s.operationRouteCompanies.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "company_id": r.Params.CompanyId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListOperationRouteCompanies200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetOperationRouteCompany(ctx context.Context, r api.AdminGetOperationRouteCompanyRequestObject) (api.AdminGetOperationRouteCompanyResponseObject, error) {
	m, err := s.operationRouteCompanies.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetOperationRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminCreateOperationRouteCompany(ctx context.Context, r api.AdminCreateOperationRouteCompanyRequestObject) (api.AdminCreateOperationRouteCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteCompanies.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateOperationRouteCompany201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateOperationRouteCompany(ctx context.Context, r api.AdminUpdateOperationRouteCompanyRequestObject) (api.AdminUpdateOperationRouteCompanyResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteCompanies.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateOperationRouteCompany200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteOperationRouteCompany(ctx context.Context, r api.AdminDeleteOperationRouteCompanyRequestObject) (api.AdminDeleteOperationRouteCompanyResponseObject, error) {
	if err := s.operationRouteCompanies.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteOperationRouteCompany204Response{}, nil
}

func (s *Server) AdminGetOperationRouteCompanySchema(ctx context.Context, r api.AdminGetOperationRouteCompanySchemaRequestObject) (api.AdminGetOperationRouteCompanySchemaResponseObject, error) {
	return api.AdminGetOperationRouteCompanySchema200JSONResponse(s.schemas.For("OperationRouteCompany", string(r.Params.Action))), nil
}

// --- OperationRouteSection ---

func (s *Server) ListOperationRouteSections(ctx context.Context, r api.ListOperationRouteSectionsRequestObject) (api.ListOperationRouteSectionsResponseObject, error) {
	items, next, err := s.operationRouteSections.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "route_id": r.Params.RouteId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListOperationRouteSections200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetOperationRouteSection(ctx context.Context, r api.GetOperationRouteSectionRequestObject) (api.GetOperationRouteSectionResponseObject, error) {
	m, err := s.operationRouteSections.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetOperationRouteSection200JSONResponse(*m), nil
}

func (s *Server) AdminListOperationRouteSections(ctx context.Context, r api.AdminListOperationRouteSectionsRequestObject) (api.AdminListOperationRouteSectionsResponseObject, error) {
	items, next, err := s.operationRouteSections.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "route_id": r.Params.RouteId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListOperationRouteSections200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetOperationRouteSection(ctx context.Context, r api.AdminGetOperationRouteSectionRequestObject) (api.AdminGetOperationRouteSectionResponseObject, error) {
	m, err := s.operationRouteSections.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetOperationRouteSection200JSONResponse(*m), nil
}

func (s *Server) AdminCreateOperationRouteSection(ctx context.Context, r api.AdminCreateOperationRouteSectionRequestObject) (api.AdminCreateOperationRouteSectionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteSections.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateOperationRouteSection201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateOperationRouteSection(ctx context.Context, r api.AdminUpdateOperationRouteSectionRequestObject) (api.AdminUpdateOperationRouteSectionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteSections.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateOperationRouteSection200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteOperationRouteSection(ctx context.Context, r api.AdminDeleteOperationRouteSectionRequestObject) (api.AdminDeleteOperationRouteSectionResponseObject, error) {
	if err := s.operationRouteSections.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteOperationRouteSection204Response{}, nil
}

func (s *Server) AdminGetOperationRouteSectionSchema(ctx context.Context, r api.AdminGetOperationRouteSectionSchemaRequestObject) (api.AdminGetOperationRouteSectionSchemaResponseObject, error) {
	return api.AdminGetOperationRouteSectionSchema200JSONResponse(s.schemas.For("OperationRouteSection", string(r.Params.Action))), nil
}

// --- OperationRouteStop ---

func (s *Server) ListOperationRouteStops(ctx context.Context, r api.ListOperationRouteStopsRequestObject) (api.ListOperationRouteStopsResponseObject, error) {
	items, next, err := s.operationRouteStops.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListOperationRouteStops200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetOperationRouteStop(ctx context.Context, r api.GetOperationRouteStopRequestObject) (api.GetOperationRouteStopResponseObject, error) {
	m, err := s.operationRouteStops.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetOperationRouteStop200JSONResponse(*m), nil
}

func (s *Server) AdminListOperationRouteStops(ctx context.Context, r api.AdminListOperationRouteStopsRequestObject) (api.AdminListOperationRouteStopsResponseObject, error) {
	items, next, err := s.operationRouteStops.List(ctx, repo.Filter{Eq: map[string]any{"operation_route_id": r.Params.OperationRouteId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListOperationRouteStops200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetOperationRouteStop(ctx context.Context, r api.AdminGetOperationRouteStopRequestObject) (api.AdminGetOperationRouteStopResponseObject, error) {
	m, err := s.operationRouteStops.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetOperationRouteStop200JSONResponse(*m), nil
}

func (s *Server) AdminCreateOperationRouteStop(ctx context.Context, r api.AdminCreateOperationRouteStopRequestObject) (api.AdminCreateOperationRouteStopResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteStops.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateOperationRouteStop201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateOperationRouteStop(ctx context.Context, r api.AdminUpdateOperationRouteStopRequestObject) (api.AdminUpdateOperationRouteStopResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.operationRouteStops.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateOperationRouteStop200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteOperationRouteStop(ctx context.Context, r api.AdminDeleteOperationRouteStopRequestObject) (api.AdminDeleteOperationRouteStopResponseObject, error) {
	if err := s.operationRouteStops.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteOperationRouteStop204Response{}, nil
}

func (s *Server) AdminGetOperationRouteStopSchema(ctx context.Context, r api.AdminGetOperationRouteStopSchemaRequestObject) (api.AdminGetOperationRouteStopSchemaResponseObject, error) {
	return api.AdminGetOperationRouteStopSchema200JSONResponse(s.schemas.For("OperationRouteStop", string(r.Params.Action))), nil
}

// --- TimetableVersion ---

func (s *Server) ListTimetableVersions(ctx context.Context, r api.ListTimetableVersionsRequestObject) (api.ListTimetableVersionsResponseObject, error) {
	items, next, err := s.timetableVersions.List(ctx, repo.Filter{Eq: map[string]any{"company_id": r.Params.CompanyId}, Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListTimetableVersions200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetTimetableVersion(ctx context.Context, r api.GetTimetableVersionRequestObject) (api.GetTimetableVersionResponseObject, error) {
	m, err := s.timetableVersions.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetTimetableVersion200JSONResponse(*m), nil
}

func (s *Server) AdminListTimetableVersions(ctx context.Context, r api.AdminListTimetableVersionsRequestObject) (api.AdminListTimetableVersionsResponseObject, error) {
	items, next, err := s.timetableVersions.List(ctx, repo.Filter{Eq: map[string]any{"company_id": r.Params.CompanyId}, Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListTimetableVersions200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetTimetableVersion(ctx context.Context, r api.AdminGetTimetableVersionRequestObject) (api.AdminGetTimetableVersionResponseObject, error) {
	m, err := s.timetableVersions.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetTimetableVersion200JSONResponse(*m), nil
}

func (s *Server) AdminCreateTimetableVersion(ctx context.Context, r api.AdminCreateTimetableVersionRequestObject) (api.AdminCreateTimetableVersionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.timetableVersions.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateTimetableVersion201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateTimetableVersion(ctx context.Context, r api.AdminUpdateTimetableVersionRequestObject) (api.AdminUpdateTimetableVersionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.timetableVersions.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateTimetableVersion200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteTimetableVersion(ctx context.Context, r api.AdminDeleteTimetableVersionRequestObject) (api.AdminDeleteTimetableVersionResponseObject, error) {
	if err := s.timetableVersions.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteTimetableVersion204Response{}, nil
}

func (s *Server) AdminGetTimetableVersionSchema(ctx context.Context, r api.AdminGetTimetableVersionSchemaRequestObject) (api.AdminGetTimetableVersionSchemaResponseObject, error) {
	return api.AdminGetTimetableVersionSchema200JSONResponse(s.schemas.For("TimetableVersion", string(r.Params.Action))), nil
}

// --- ServiceCalendar ---

func (s *Server) ListServiceCalendars(ctx context.Context, r api.ListServiceCalendarsRequestObject) (api.ListServiceCalendarsResponseObject, error) {
	items, next, err := s.serviceCalendars.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListServiceCalendars200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetServiceCalendar(ctx context.Context, r api.GetServiceCalendarRequestObject) (api.GetServiceCalendarResponseObject, error) {
	m, err := s.serviceCalendars.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetServiceCalendar200JSONResponse(*m), nil
}

func (s *Server) AdminListServiceCalendars(ctx context.Context, r api.AdminListServiceCalendarsRequestObject) (api.AdminListServiceCalendarsResponseObject, error) {
	items, next, err := s.serviceCalendars.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListServiceCalendars200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetServiceCalendar(ctx context.Context, r api.AdminGetServiceCalendarRequestObject) (api.AdminGetServiceCalendarResponseObject, error) {
	m, err := s.serviceCalendars.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetServiceCalendar200JSONResponse(*m), nil
}

func (s *Server) AdminCreateServiceCalendar(ctx context.Context, r api.AdminCreateServiceCalendarRequestObject) (api.AdminCreateServiceCalendarResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.serviceCalendars.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateServiceCalendar201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateServiceCalendar(ctx context.Context, r api.AdminUpdateServiceCalendarRequestObject) (api.AdminUpdateServiceCalendarResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.serviceCalendars.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateServiceCalendar200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteServiceCalendar(ctx context.Context, r api.AdminDeleteServiceCalendarRequestObject) (api.AdminDeleteServiceCalendarResponseObject, error) {
	if err := s.serviceCalendars.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteServiceCalendar204Response{}, nil
}

func (s *Server) AdminGetServiceCalendarSchema(ctx context.Context, r api.AdminGetServiceCalendarSchemaRequestObject) (api.AdminGetServiceCalendarSchemaResponseObject, error) {
	return api.AdminGetServiceCalendarSchema200JSONResponse(s.schemas.For("ServiceCalendar", string(r.Params.Action))), nil
}

// --- ServiceCalendarException ---

func (s *Server) ListServiceCalendarExceptions(ctx context.Context, r api.ListServiceCalendarExceptionsRequestObject) (api.ListServiceCalendarExceptionsResponseObject, error) {
	items, next, err := s.serviceCalendarExceptions.List(ctx, repo.Filter{Eq: map[string]any{"calendar_id": r.Params.CalendarId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListServiceCalendarExceptions200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetServiceCalendarException(ctx context.Context, r api.GetServiceCalendarExceptionRequestObject) (api.GetServiceCalendarExceptionResponseObject, error) {
	m, err := s.serviceCalendarExceptions.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetServiceCalendarException200JSONResponse(*m), nil
}

func (s *Server) AdminListServiceCalendarExceptions(ctx context.Context, r api.AdminListServiceCalendarExceptionsRequestObject) (api.AdminListServiceCalendarExceptionsResponseObject, error) {
	items, next, err := s.serviceCalendarExceptions.List(ctx, repo.Filter{Eq: map[string]any{"calendar_id": r.Params.CalendarId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListServiceCalendarExceptions200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetServiceCalendarException(ctx context.Context, r api.AdminGetServiceCalendarExceptionRequestObject) (api.AdminGetServiceCalendarExceptionResponseObject, error) {
	m, err := s.serviceCalendarExceptions.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetServiceCalendarException200JSONResponse(*m), nil
}

func (s *Server) AdminCreateServiceCalendarException(ctx context.Context, r api.AdminCreateServiceCalendarExceptionRequestObject) (api.AdminCreateServiceCalendarExceptionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.serviceCalendarExceptions.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateServiceCalendarException201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateServiceCalendarException(ctx context.Context, r api.AdminUpdateServiceCalendarExceptionRequestObject) (api.AdminUpdateServiceCalendarExceptionResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.serviceCalendarExceptions.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateServiceCalendarException200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteServiceCalendarException(ctx context.Context, r api.AdminDeleteServiceCalendarExceptionRequestObject) (api.AdminDeleteServiceCalendarExceptionResponseObject, error) {
	if err := s.serviceCalendarExceptions.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteServiceCalendarException204Response{}, nil
}

func (s *Server) AdminGetServiceCalendarExceptionSchema(ctx context.Context, r api.AdminGetServiceCalendarExceptionSchemaRequestObject) (api.AdminGetServiceCalendarExceptionSchemaResponseObject, error) {
	return api.AdminGetServiceCalendarExceptionSchema200JSONResponse(s.schemas.For("ServiceCalendarException", string(r.Params.Action))), nil
}

// --- Train ---

func (s *Server) ListTrains(ctx context.Context, r api.ListTrainsRequestObject) (api.ListTrainsResponseObject, error) {
	items, next, err := s.trains.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListTrains200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetTrain(ctx context.Context, r api.GetTrainRequestObject) (api.GetTrainResponseObject, error) {
	m, err := s.trains.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetTrain200JSONResponse(*m), nil
}

func (s *Server) AdminListTrains(ctx context.Context, r api.AdminListTrainsRequestObject) (api.AdminListTrainsResponseObject, error) {
	items, next, err := s.trains.List(ctx, repo.Filter{Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListTrains200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetTrain(ctx context.Context, r api.AdminGetTrainRequestObject) (api.AdminGetTrainResponseObject, error) {
	m, err := s.trains.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetTrain200JSONResponse(*m), nil
}

func (s *Server) AdminCreateTrain(ctx context.Context, r api.AdminCreateTrainRequestObject) (api.AdminCreateTrainResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trains.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateTrain201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateTrain(ctx context.Context, r api.AdminUpdateTrainRequestObject) (api.AdminUpdateTrainResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trains.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateTrain200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteTrain(ctx context.Context, r api.AdminDeleteTrainRequestObject) (api.AdminDeleteTrainResponseObject, error) {
	if err := s.trains.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteTrain204Response{}, nil
}

func (s *Server) AdminGetTrainSchema(ctx context.Context, r api.AdminGetTrainSchemaRequestObject) (api.AdminGetTrainSchemaResponseObject, error) {
	return api.AdminGetTrainSchema200JSONResponse(s.schemas.For("Train", string(r.Params.Action))), nil
}

// --- TrainRun ---

func (s *Server) ListTrainRuns(ctx context.Context, r api.ListTrainRunsRequestObject) (api.ListTrainRunsResponseObject, error) {
	items, next, err := s.trainRuns.List(ctx, repo.Filter{Eq: map[string]any{"timetable_version_id": r.Params.TimetableVersionId, "operation_route_id": r.Params.OperationRouteId, "train_id": r.Params.TrainId, "calendar_id": r.Params.CalendarId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListTrainRuns200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetTrainRun(ctx context.Context, r api.GetTrainRunRequestObject) (api.GetTrainRunResponseObject, error) {
	m, err := s.trainRuns.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetTrainRun200JSONResponse(*m), nil
}

func (s *Server) AdminListTrainRuns(ctx context.Context, r api.AdminListTrainRunsRequestObject) (api.AdminListTrainRunsResponseObject, error) {
	items, next, err := s.trainRuns.List(ctx, repo.Filter{Eq: map[string]any{"timetable_version_id": r.Params.TimetableVersionId, "operation_route_id": r.Params.OperationRouteId, "train_id": r.Params.TrainId, "calendar_id": r.Params.CalendarId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListTrainRuns200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetTrainRun(ctx context.Context, r api.AdminGetTrainRunRequestObject) (api.AdminGetTrainRunResponseObject, error) {
	m, err := s.trainRuns.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetTrainRun200JSONResponse(*m), nil
}

func (s *Server) AdminCreateTrainRun(ctx context.Context, r api.AdminCreateTrainRunRequestObject) (api.AdminCreateTrainRunResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trainRuns.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateTrainRun201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateTrainRun(ctx context.Context, r api.AdminUpdateTrainRunRequestObject) (api.AdminUpdateTrainRunResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trainRuns.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateTrainRun200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteTrainRun(ctx context.Context, r api.AdminDeleteTrainRunRequestObject) (api.AdminDeleteTrainRunResponseObject, error) {
	if err := s.trainRuns.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteTrainRun204Response{}, nil
}

func (s *Server) AdminGetTrainRunSchema(ctx context.Context, r api.AdminGetTrainRunSchemaRequestObject) (api.AdminGetTrainRunSchemaResponseObject, error) {
	return api.AdminGetTrainRunSchema200JSONResponse(s.schemas.For("TrainRun", string(r.Params.Action))), nil
}

// --- TrainRunStop ---

func (s *Server) ListTrainRunStops(ctx context.Context, r api.ListTrainRunStopsRequestObject) (api.ListTrainRunStopsResponseObject, error) {
	items, next, err := s.trainRunStops.List(ctx, repo.Filter{Eq: map[string]any{"train_run_id": r.Params.TrainRunId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListTrainRunStops200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetTrainRunStop(ctx context.Context, r api.GetTrainRunStopRequestObject) (api.GetTrainRunStopResponseObject, error) {
	m, err := s.trainRunStops.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetTrainRunStop200JSONResponse(*m), nil
}

func (s *Server) AdminListTrainRunStops(ctx context.Context, r api.AdminListTrainRunStopsRequestObject) (api.AdminListTrainRunStopsResponseObject, error) {
	items, next, err := s.trainRunStops.List(ctx, repo.Filter{Eq: map[string]any{"train_run_id": r.Params.TrainRunId, "station_id": r.Params.StationId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListTrainRunStops200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetTrainRunStop(ctx context.Context, r api.AdminGetTrainRunStopRequestObject) (api.AdminGetTrainRunStopResponseObject, error) {
	m, err := s.trainRunStops.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetTrainRunStop200JSONResponse(*m), nil
}

func (s *Server) AdminCreateTrainRunStop(ctx context.Context, r api.AdminCreateTrainRunStopRequestObject) (api.AdminCreateTrainRunStopResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trainRunStops.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateTrainRunStop201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateTrainRunStop(ctx context.Context, r api.AdminUpdateTrainRunStopRequestObject) (api.AdminUpdateTrainRunStopResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.trainRunStops.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateTrainRunStop200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteTrainRunStop(ctx context.Context, r api.AdminDeleteTrainRunStopRequestObject) (api.AdminDeleteTrainRunStopResponseObject, error) {
	if err := s.trainRunStops.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteTrainRunStop204Response{}, nil
}

func (s *Server) AdminGetTrainRunStopSchema(ctx context.Context, r api.AdminGetTrainRunStopSchemaRequestObject) (api.AdminGetTrainRunStopSchemaResponseObject, error) {
	return api.AdminGetTrainRunStopSchema200JSONResponse(s.schemas.For("TrainRunStop", string(r.Params.Action))), nil
}

// --- Media ---

func (s *Server) ListMedia(ctx context.Context, r api.ListMediaRequestObject) (api.ListMediaResponseObject, error) {
	items, next, err := s.media.List(ctx, repo.Filter{Eq: map[string]any{"media_type": r.Params.MediaType}, Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListMedia200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetMedia(ctx context.Context, r api.GetMediaRequestObject) (api.GetMediaResponseObject, error) {
	m, err := s.media.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetMedia200JSONResponse(*m), nil
}

func (s *Server) AdminListMedia(ctx context.Context, r api.AdminListMediaRequestObject) (api.AdminListMediaResponseObject, error) {
	items, next, err := s.media.List(ctx, repo.Filter{Eq: map[string]any{"media_type": r.Params.MediaType}, Q: r.Params.Q, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListMedia200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetMedia(ctx context.Context, r api.AdminGetMediaRequestObject) (api.AdminGetMediaResponseObject, error) {
	m, err := s.media.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetMedia200JSONResponse(*m), nil
}

func (s *Server) AdminCreateMedia(ctx context.Context, r api.AdminCreateMediaRequestObject) (api.AdminCreateMediaResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.media.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateMedia201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateMedia(ctx context.Context, r api.AdminUpdateMediaRequestObject) (api.AdminUpdateMediaResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.media.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateMedia200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteMedia(ctx context.Context, r api.AdminDeleteMediaRequestObject) (api.AdminDeleteMediaResponseObject, error) {
	if err := s.media.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteMedia204Response{}, nil
}

func (s *Server) AdminGetMediaSchema(ctx context.Context, r api.AdminGetMediaSchemaRequestObject) (api.AdminGetMediaSchemaResponseObject, error) {
	return api.AdminGetMediaSchema200JSONResponse(s.schemas.For("Media", string(r.Params.Action))), nil
}

// --- MediaAttachment ---

func (s *Server) ListMediaAttachments(ctx context.Context, r api.ListMediaAttachmentsRequestObject) (api.ListMediaAttachmentsResponseObject, error) {
	items, next, err := s.mediaAttachments.List(ctx, repo.Filter{Eq: map[string]any{"media_id": r.Params.MediaId, "entity_type": r.Params.EntityType, "entity_id": r.Params.EntityId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.ListMediaAttachments200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) GetMediaAttachment(ctx context.Context, r api.GetMediaAttachmentRequestObject) (api.GetMediaAttachmentResponseObject, error) {
	m, err := s.mediaAttachments.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.GetMediaAttachment200JSONResponse(*m), nil
}

func (s *Server) AdminListMediaAttachments(ctx context.Context, r api.AdminListMediaAttachmentsRequestObject) (api.AdminListMediaAttachmentsResponseObject, error) {
	items, next, err := s.mediaAttachments.List(ctx, repo.Filter{Eq: map[string]any{"media_id": r.Params.MediaId, "entity_type": r.Params.EntityType, "entity_id": r.Params.EntityId}, Cursor: r.Params.Cursor, Limit: r.Params.Limit})
	if err != nil {
		return nil, err
	}
	return api.AdminListMediaAttachments200JSONResponse{Items: items, Pagination: api.Pagination{Next: next}}, nil
}

func (s *Server) AdminGetMediaAttachment(ctx context.Context, r api.AdminGetMediaAttachmentRequestObject) (api.AdminGetMediaAttachmentResponseObject, error) {
	m, err := s.mediaAttachments.Get(ctx, r.Id.String())
	if err != nil {
		return nil, err
	}
	return api.AdminGetMediaAttachment200JSONResponse(*m), nil
}

func (s *Server) AdminCreateMediaAttachment(ctx context.Context, r api.AdminCreateMediaAttachmentRequestObject) (api.AdminCreateMediaAttachmentResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.mediaAttachments.Create(ctx, r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminCreateMediaAttachment201JSONResponse(*m), nil
}

func (s *Server) AdminUpdateMediaAttachment(ctx context.Context, r api.AdminUpdateMediaAttachmentRequestObject) (api.AdminUpdateMediaAttachmentResponseObject, error) {
	if r.Body == nil {
		return nil, repo.ErrBadRequest
	}
	m, err := s.mediaAttachments.Update(ctx, r.Id.String(), r.Body)
	if err != nil {
		return nil, err
	}
	return api.AdminUpdateMediaAttachment200JSONResponse(*m), nil
}

func (s *Server) AdminDeleteMediaAttachment(ctx context.Context, r api.AdminDeleteMediaAttachmentRequestObject) (api.AdminDeleteMediaAttachmentResponseObject, error) {
	if err := s.mediaAttachments.Delete(ctx, r.Id.String()); err != nil {
		return nil, err
	}
	return api.AdminDeleteMediaAttachment204Response{}, nil
}

func (s *Server) AdminGetMediaAttachmentSchema(ctx context.Context, r api.AdminGetMediaAttachmentSchemaRequestObject) (api.AdminGetMediaAttachmentSchemaResponseObject, error) {
	return api.AdminGetMediaAttachmentSchema200JSONResponse(s.schemas.For("MediaAttachment", string(r.Params.Action))), nil
}
